{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "啟動伺服器樣板\n",
    "'''\n",
    "from flask import Flask,request,abort\n",
    "from linebot import LineBotApi,WebhookHandler\n",
    "from linebot.exceptions import InvalidSignatureError\n",
    "import json\n",
    "\n",
    "secret_file = json.load(open('line_bot_secret_key.json','r'))\n",
    "server_url = secret_file.get('server_url')\n",
    "app = Flask(__name__,static_url_path='/image_trpg_elevator',static_folder='../image_trpg_elevator/')\n",
    "\n",
    "line_bot_api = LineBotApi(secret_file.get(\"channel_access_token\"))\n",
    "handler = WebhookHandler(secret_file.get('secret_key'))\n",
    "\n",
    "@app.route('/',methods = ['POST'])\n",
    "def callback():\n",
    "    signature = request.headers['X-Link-Signature']\n",
    "    body = request.get_data(as_text=True)\n",
    "    app.logger.info('Request body:' + body)\n",
    "\n",
    "    try:\n",
    "        handler.handle(body,signature)\n",
    "    except:\n",
    "        abort(400)\n",
    "    return \"OK\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "from linebot.models import TextSendMessage,ImageSendMessage,MessageEvent,TextMessage\n",
    "# 消息製作\n",
    "reply_message_list = [\n",
    "# ImageSendMessage(original_content_url='https://{}/warning.png'.format(server_url)),\n",
    "    TextSendMessage(text='本遊戲含有恐怖及克蘇魯神話成分，請斟酌遊玩')\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from linebot.models.events import FollowEvent\n",
    "import requests\n",
    "\n",
    "# 這裡是在做發消息及取個資的動作\n",
    "\n",
    "@handler.add(FollowEvent)\n",
    "def reply_user_and_get_user_id(event):\n",
    "    user_profile = line_bot_api.get_profile(event.source.user_id)\n",
    "    with open('../users_profile.txt','a') as us_file:\n",
    "        us_file.write(json.dumps(vars(user_profile),sort_keys=True))\n",
    "        us_file.write('\\r\\n')\n",
    "\n",
    "    # 綁定圖文選單\n",
    "    LineRichMenuMainID = secret_file.get('rich_menu_id')\n",
    "    linkResult = line_bot_api.link_rich_menu_to_user(secret_file[\"self_user_id\"],LineRichMenuMainID)\n",
    "\n",
    "    # 關注回應\n",
    "    line_bot_api.reply_message(\n",
    "        event.reply_token,\n",
    "        reply_message_list\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)\n",
      "[2019-11-23 11:57:14,362] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-5-bf9acd4c1980>\", line 18, in callback\n",
      "    signature = request.headers['X-Link-Signature']\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\werkzeug\\datastructures.py\", line 1375, in __getitem__\n",
      "    return _unicodify_header_value(self.environ[\"HTTP_\" + key])\n",
      "KeyError: 'HTTP_X_LINK_SIGNATURE'\n",
      "127.0.0.1 - - [23/Nov/2019 11:57:14] \"POST / HTTP/1.1\" 500 -\n",
      "[2019-11-23 11:57:15,186] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-5-bf9acd4c1980>\", line 18, in callback\n",
      "    signature = request.headers['X-Link-Signature']\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\werkzeug\\datastructures.py\", line 1375, in __getitem__\n",
      "    return _unicodify_header_value(self.environ[\"HTTP_\" + key])\n",
      "KeyError: 'HTTP_X_LINK_SIGNATURE'\n",
      "127.0.0.1 - - [23/Nov/2019 11:57:15] \"POST / HTTP/1.1\" 500 -\n",
      "[2019-11-23 11:57:30,233] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-5-bf9acd4c1980>\", line 18, in callback\n",
      "    signature = request.headers['X-Link-Signature']\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\werkzeug\\datastructures.py\", line 1375, in __getitem__\n",
      "    return _unicodify_header_value(self.environ[\"HTTP_\" + key])\n",
      "KeyError: 'HTTP_X_LINK_SIGNATURE'\n",
      "127.0.0.1 - - [23/Nov/2019 11:57:30] \"POST / HTTP/1.1\" 500 -\n",
      "[2019-11-23 11:57:32,692] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-5-bf9acd4c1980>\", line 18, in callback\n",
      "    signature = request.headers['X-Link-Signature']\n",
      "  File \"C:\\Users\\max36\\Anaconda3\\lib\\site-packages\\werkzeug\\datastructures.py\", line 1375, in __getitem__\n",
      "    return _unicodify_header_value(self.environ[\"HTTP_\" + key])\n",
      "KeyError: 'HTTP_X_LINK_SIGNATURE'\n",
      "127.0.0.1 - - [23/Nov/2019 11:57:32] \"POST / HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "if __name__ =='__main__':\n",
    "    app.run(host = '0.0.0.0')"
   ]
  }
 ],
 "metadata": {
  "file_extension": ".py",
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  },
  "mimetype": "text/x-python",
  "name": "python",
  "npconvert_exporter": "python",
  "pygments_lexer": "ipython3",
  "version": 3
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
